#include "crc_test.h"

int errors = 0;
int passed = 0;
int percents;

int main(void) {
    printf("test libcrc ver." CRC_VERSION_STRING "\n");
    crc_test(CRC3_GSM);
    crc_test(CRC3_ROHC);
    crc_test(CRC4_G_704);
    crc_test(CRC4_INTERLAKEN);
    crc_test(CRC5_EPC_C1G2);
    crc_test(CRC5_G_704);
    crc_test(CRC5_USB);
    crc_test(CRC6_CDMA2000_A);
    crc_test(CRC6_CDMA2000_B);
    crc_test(CRC6_DARC);
    crc_test(CRC6_G_704);
    crc_test(CRC6_GSM);
    crc_test(CRC7_MMC);
    crc_test(CRC7_ROHC);
    crc_test(CRC7_UMTS);
    crc_test(CRC8_AUTOSAR);
    crc_test(CRC8_BLUETOOTH);
    crc_test(CRC8_CDMA2000);
    crc_test(CRC8_DARC);
    crc_test(CRC8_DVB_S2);
    crc_test(CRC8_GSM_A);
    crc_test(CRC8_GSM_B);
    crc_test(CRC8_HITAG);
    crc_test(CRC8_I_432_1);
    crc_test(CRC8_I_CODE);
    crc_test(CRC8_LTE);
    crc_test(CRC8_MAXIM_DOW);
    crc_test(CRC8_MIFARE_MAD);
    crc_test(CRC8_NRSC_5);
    crc_test(CRC8_OPENSAFETY);
    crc_test(CRC8_ROHC);
    crc_test(CRC8_SAE_J1850);
    crc_test(CRC8_SMBUS);
    crc_test(CRC8_TECH_3250);
    crc_test(CRC8_WCDMA);
    crc_test(CRC10_ATM);
    crc_test(CRC10_CDMA2000);
    crc_test(CRC10_GSM);
    crc_test(CRC11_FLEXRAY);
    crc_test(CRC11_UMTS);
    crc_test(CRC12_CDMA2000);
    crc_test(CRC12_DECT);
    crc_test(CRC12_GSM);
    crc_test(CRC12_UMTS);
    crc_test(CRC13_BBC);
    crc_test(CRC14_DARC);
    crc_test(CRC14_GSM);
    crc_test(CRC15_CAN);
    crc_test(CRC15_MPT1327);
    crc_test(CRC16_ARC);
    crc_test(CRC16_CDMA2000);
    crc_test(CRC16_CMS);
    crc_test(CRC16_DDS_110);
    crc_test(CRC16_DECT_R);
    crc_test(CRC16_DECT_X);
    crc_test(CRC16_DNP);
    crc_test(CRC16_EN_13757);
    crc_test(CRC16_GENIBUS);
    crc_test(CRC16_GSM);
    crc_test(CRC16_IBM_3740);
    crc_test(CRC16_IBM_SDLC);
    crc_test(CRC16_ISO_IEC_14443_3_A);
    crc_test(CRC16_KERMIT);
    crc_test(CRC16_LJ1200);
    crc_test(CRC16_M17);
    crc_test(CRC16_MAXIM_DOW);
    crc_test(CRC16_MCRF4XX);
    crc_test(CRC16_MODBUS);
    crc_test(CRC16_NRSC_5);
    crc_test(CRC16_OPENSAFETY_A);
    crc_test(CRC16_OPENSAFETY_B);
    crc_test(CRC16_PROFIBUS);
    crc_test(CRC16_RIELLO);
    crc_test(CRC16_SPI_FUJITSU);
    crc_test(CRC16_T10_DIF);
    crc_test(CRC16_TELEDISK);
    crc_test(CRC16_TMS37157);
    crc_test(CRC16_UMTS);
    crc_test(CRC16_USB);
    crc_test(CRC16_XMODEM);
    crc_test(CRC17_CAN_FD);
    crc_test(CRC21_CAN_FD);
    crc_test(CRC24_BLE);
    crc_test(CRC24_FLEXRAY_A);
    crc_test(CRC24_FLEXRAY_B);
    crc_test(CRC24_INTERLAKEN);
    crc_test(CRC24_LTE_A);
    crc_test(CRC24_LTE_B);
    crc_test(CRC24_OPENPGP);
    crc_test(CRC24_OS_9);
    crc_test(CRC30_CDMA);
    crc_test(CRC31_PHILIPS);
    crc_test(CRC32_AIXM);
    crc_test(CRC32_AUTOSAR);
    crc_test(CRC32_BASE91_D);
    crc_test(CRC32_BZIP2);
    crc_test(CRC32_CD_ROM_EDC);
    crc_test(CRC32_CKSUM);
    crc_test(CRC32_ISCSI);
    crc_test(CRC32_ISO_HDLC);
    crc_test(CRC32_JAMCRC);
    crc_test(CRC32_MEF);
    crc_test(CRC32_MPEG_2);
    crc_test(CRC32_XFER);
    crc_test(CRC40_GSM);
    crc_test(CRC64_ECMA_182);
    crc_test(CRC64_GO_ISO);
    crc_test(CRC64_MS);
    crc_test(CRC64_NVME);
    crc_test(CRC64_REDIS);
    crc_test(CRC64_WE);
    crc_test(CRC64_XZ);

#if CRC_HAS_128BIT_ALGO
    crc_test(CRC82_DARC);
#endif

    percents = 100 * passed / (passed + errors);
    printf("[%d%%] tests passed, %d errors\n", percents, errors);

    return 0;
}
